binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions:
  TemplateHaskell: true
  OverloadedStrings: true
  QuasiQuotes: true
  TypeFamilies: true
  MultiParamTypeClasses: true
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Git: https://github.com/JoeyEremondi/ai-vs-ai-common.git 8ba15a730120896baf07ed6f1b29f2446b4cea34

  Hackage : astar 0.2.1

'
ghc-args:
- -v
excluded-modules: []
